name: Deploy

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.0
        with:
          deno-version: v1.x

      - name: Verify formatting
        run: deno fmt --check

      - name: Run tests
        run: deno test --unstable --allow-net --allow-env --allow-read --allow-write

  deploy:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: marcosadriano05-delivery
          entrypoint: src/main/server.ts
      
      - name: Run migrations
        run: deno run -A --unstable https://deno.land/x/nessie/cli.ts migrate

      - name: Run seeds
        run: deno run -A --unstable https://deno.land/x/nessie/cli.ts seed